# Branch coverage for core/MsvcVcvarsConfig.cmake pure helpers (no compiler).
include("${MODULE_ROOT}/core/MsvcVcvarsConfig.cmake")

function(_expect_eq got expected label)
  if(NOT "${got}" STREQUAL "${expected}")
    message(FATAL_ERROR "${label}: expected '${expected}', got '${got}'")
  endif()
endfunction()

# --- _msvc_vcvars_first_line ---
_msvc_vcvars_first_line("line1\nline2\nline3" _r)
_expect_eq("${_r}" "line1" "first_line LF")
_msvc_vcvars_first_line("first\r\nsecond\r\nthird" _r)
_expect_eq("${_r}" "first" "first_line CRLF")
_msvc_vcvars_first_line("  spaced  \nnext" _r)
_expect_eq("${_r}" "spaced" "first_line strip")

# --- _msvc_vcvars_abbrev_env ---
set(ENV{__CT_TEST_ENV} "")
_msvc_vcvars_abbrev_env(__CT_TEST_ENV _r)
_expect_eq("${_r}" "(unset)" "abbrev unset")
set(ENV{__CT_TEST_ENV} "C:/one")
_msvc_vcvars_abbrev_env(__CT_TEST_ENV _r)
_expect_eq("${_r}" "C:/one" "abbrev single")
set(ENV{__CT_TEST_ENV} "C:/a;C:/b;C:/c")
_msvc_vcvars_abbrev_env(__CT_TEST_ENV _r)
_expect_eq("${_r}" "C:/a ... (3 entries)" "abbrev multi")

# --- _msvc_vcvars_detect_host_arch ---
set(ENV{PROCESSOR_ARCHITEW6432} "AMD64")
_msvc_vcvars_detect_host_arch(_r)
_expect_eq("${_r}" "x64" "host AMD64")
set(ENV{PROCESSOR_ARCHITEW6432} "")
set(ENV{PROCESSOR_ARCHITECTURE} "ARM64")
_msvc_vcvars_detect_host_arch(_r)
_expect_eq("${_r}" "arm64" "host ARM64")
set(ENV{PROCESSOR_ARCHITECTURE} "x86")
_msvc_vcvars_detect_host_arch(_r)
_expect_eq("${_r}" "x86" "host x86")

# --- _msvc_vcvars_normalize_target ---
_msvc_vcvars_normalize_target("x64" "x64" _t _raw)
_expect_eq("${_t}" "x64" "norm x64")
_expect_eq("${_raw}" "FALSE" "norm x64 raw")
_msvc_vcvars_normalize_target("amd64" "x64" _t _raw)
_expect_eq("${_t}" "x64" "norm amd64")
_msvc_vcvars_normalize_target("win32" "x64" _t _raw)
_expect_eq("${_t}" "x86" "norm win32")
_msvc_vcvars_normalize_target("aarch64" "x64" _t _raw)
_expect_eq("${_t}" "arm64" "norm aarch64")
_msvc_vcvars_normalize_target("" "arm64" _t _raw)
_expect_eq("${_t}" "arm64" "norm empty -> host")
_msvc_vcvars_normalize_target("amd64_x86" "x64" _t _raw)
_expect_eq("${_t}" "amd64_x86" "norm raw token")
_expect_eq("${_raw}" "TRUE" "norm raw flag")

# --- _msvc_vcvars_compute_arg ---
_msvc_vcvars_compute_arg("x64" "x64" FALSE _r)
_expect_eq("${_r}" "amd64" "arg x64->x64")
_msvc_vcvars_compute_arg("x64" "x86" FALSE _r)
_expect_eq("${_r}" "amd64_x86" "arg x64->x86")
_msvc_vcvars_compute_arg("x64" "arm64" FALSE _r)
_expect_eq("${_r}" "amd64_arm64" "arg x64->arm64")
_msvc_vcvars_compute_arg("arm64" "arm64" FALSE _r)
_expect_eq("${_r}" "arm64" "arg arm64->arm64")
_msvc_vcvars_compute_arg("arm64" "x64" FALSE _r)
_expect_eq("${_r}" "arm64_amd64" "arg arm64->x64")
_msvc_vcvars_compute_arg("arm64" "x86" FALSE _r)
_expect_eq("${_r}" "arm64_x86" "arg arm64->x86")
_msvc_vcvars_compute_arg("x86" "x86" FALSE _r)
_expect_eq("${_r}" "x86" "arg x86->x86")
_msvc_vcvars_compute_arg("x86" "x64" FALSE _r)
_expect_eq("${_r}" "" "arg x86->x64 (unsupported)")
_msvc_vcvars_compute_arg("x64" "foo" TRUE _r)
_expect_eq("${_r}" "foo" "arg raw pass-through")

# --- _msvc_vcvars_check_host_can_run (OK paths) ---
_msvc_vcvars_check_host_can_run("x64" "amd64")
_msvc_vcvars_check_host_can_run("x86" "x86")

# --- _msvc_vcvars_install_root_from_vcvarsall ---
_msvc_vcvars_install_root_from_vcvarsall("C:/VS/Community/VC/Auxiliary/Build/vcvarsall.bat" _r)
_expect_eq("${_r}" "C:/VS/Community" "install root")

# --- _msvc_vcvars_is_msvc_frontend ---
_msvc_vcvars_is_msvc_frontend("" _r)
_expect_eq("${_r}" "TRUE" "frontend empty")
_msvc_vcvars_is_msvc_frontend("C:/x/cl.exe" _r)
_expect_eq("${_r}" "TRUE" "frontend cl.exe")
_msvc_vcvars_is_msvc_frontend("clang-cl.exe" _r)
_expect_eq("${_r}" "TRUE" "frontend clang-cl")
_msvc_vcvars_is_msvc_frontend("g++" _r)
_expect_eq("${_r}" "FALSE" "frontend g++")
_msvc_vcvars_is_msvc_frontend("clang++" _r)
_expect_eq("${_r}" "FALSE" "frontend clang++")

# --- _msvc_vcvars_wants_msvc_sysroot ---
set(CMAKE_C_COMPILER "")
set(CMAKE_CXX_COMPILER "")
_msvc_vcvars_wants_msvc_sysroot(_r)
_expect_eq("${_r}" "TRUE" "sysroot both unset")
set(CMAKE_C_COMPILER "cl.exe")
set(CMAKE_CXX_COMPILER "cl.exe")
_msvc_vcvars_wants_msvc_sysroot(_r)
_expect_eq("${_r}" "TRUE" "sysroot cl+cl")
set(CMAKE_C_COMPILER "cl.exe")
set(CMAKE_CXX_COMPILER "g++")
_msvc_vcvars_wants_msvc_sysroot(_r)
_expect_eq("${_r}" "FALSE" "sysroot cl+g++")
